[programs.localnet]
anchor_shared_vault = "3eC59jD55nX6HvYj6tE7ycbmj8ctBiGuCjLBvK6oFNz9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/iulian/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
